name: Workflow Sample
on: [push]
jobs:
  workflow-jobs:
    runs-on: codebuild-github_actions_integrations-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
      - run: aws sts get-caller-identity
      - run: aws s3 ls
      
