name: Workflow Sample
run-name: Download public docker images with specified versions and upload to its corresponding ECR
on:
  workflow_dispatch:
    inputs:
      image:
        type: string
        description: Docker image name as seen in Docker Hub
        required: true
      version:
        type: string
        description: Docker image version
        required: true
      skip_trivey:
        type: boolean
        description: Skip Trivy check?
        default: false
        required: true
jobs:
  workflow-jobs:
  runs-on: ubuntu-latest
    steps:
      - name: checkout
        if: ${{ github.event.inputs.skip_trivey == 'true' }}
        run: aws sts get-caller-identity
  
      
